calculate:
  fields:
    config_entry:
      required: true
      selector:
        config_entry:
          integration: samaraenergo
    consumptions:
      required: true
      example: "230.1 или [102.3, 43.2]"
      selector:
        object:
    date:
      example: "2024-01-01"
      selector:
        date:
