calculate:
  target:
    device:
      integration: samaraenergo
      model: "Онлайн-калькулятор"
  fields:
    zones_consumption:
      required: true
      example: "102.3,43.2"
      selector:
        text:
    date:
      example: "2024-01-01"
      selector:
        date:
